### ISSUE TITLE
Are you still maintaining org-present? Are you open to enhancements?

### ISSUE THREAD

**Issue by Kazark** [rlister/org-present#20]
Love the idea here, but I see that nothing new has been merged in quite some time, and there's a couple pull requests out there that I'd like to see merged. Also there are a few more features I have in mind that I'm interested in. Would you advise that I fork it? I like to use Spacemacs, and this comes bundled with Spacemacs, so if I'm going to fork I might at least propose to Spacemacs to switch to my fork. What do you think?

**Comment by rlister** [comment]
Hi, thanks for asking this. I have indeed been neglecting things here due to work and life commitments, so I understand your frustration. Let me see if I can get all caught up on PRs this weekend to clear the backlog.

Also happy to consider commit access for anyone interested in helping out with maintenance.

**Comment by Kazark** [comment]
Oh wow, great! Thanks so much for your response. I'm still an Emacs n00b (used Vim for a long time, then got converted by Spacemacs), but I would like to get more into contributing to the ecosystem. Don't feel pressured. I was just wondering whether you were still considering pull requests and issues. That will encourage me to experiment and play with things. Thanks.
