### ISSUE TITLE
Start hook runs after narrow resulting in issues with inline images

### ISSUE THREAD

**Issue by alwyn** [rlister/org-present#29]
I am using the org layer of Spacemacs.

When I enter org-present mode, only inline images under the current heading is displayed.

I have experimented on my system and my conclusion is that the fact that org-present-narrow is called before the hook is run, results in org-display-inline-images only affecting the current org-present page.

Switching the order fixes the problem for me.

I am hesitant in submitting it as a PR, since I would expect that this behavior would affect everybody and not just me.  Also I don't know if there are any side-effects.

**Comment by kmdouglass** [comment]
@alwyn I also just ran into this issue. I can confirm that your fix works; swapping the execution order of `org-present-narrow` and the hooks indeed seems to solve the issue for me.

**Comment by tmalsburg** [comment]
Same issue with `org-latex-preview`.  I think it's not terribly likely that users want to apply a setting only to one slide instead of all.  So perhaps, the execution order can be changed without breaking anything.  Alternatively, a new hook could be introduced that runs before narrowing down to current slide.  Either way, this seems like it could be a show-stopping bug for many users and should therefore be fixed. @alwyn, since you've already made the change, would you mind making a PR.

@rlister, cool package, thanks for sharing!

**Comment by tmalsburg** [comment]
Just saw that there is another hook, `org-present-after-navigate-functions`, which can be used preview latex formulas, e.g.:

``` elisp
(add-hook 'org-present-after-navigate-functions
          (lambda (buffer-name current-heading)
            (org-latex-preview)))
```

This solves my problem, but changing the order of narrowing and running `org-present-mode-hook` may still make sense (not sure).

**Comment by alwyn** [comment]
For images I would think it would make sense to do it up front for all to avoid any delays when switching between slides, but I'm just guessing.
